version: 2
machine:
  timezone:
    America/Los_Angeles
jobs:
  build:
    docker:
      - image: node:9.2.0
    steps:
      - checkout
      - run: cd app && npm install
      - run: cd app && npm run test.coverage
